// lib/features/editor/editor_screen.dart
import 'dart:async' hide unawaited;
import 'dart:collection';
import 'dart:convert';
import 'dart:developer' as developer;
import 'dart:math' as math;

import 'package:archive/archive.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:file_selector/file_selector.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart' show ScrollDirection;
import 'package:flutter/services.dart';
import 'package:flutter_email_sender/flutter_email_sender.dart';
import 'package:image/image.dart' as img;
import 'package:package_info_plus/package_info_plus.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:permission_handler/permission_handler.dart' as ph;
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

import 'package:bitacora_web/core/app_error.dart';
import 'package:bitacora_web/core/editor_atomic_snapshot_store.dart';
import 'package:bitacora_web/core/sync/outbox_op.dart';
import 'package:bitacora_web/core/sync/outbox_store.dart';
import 'package:bitacora_web/core/sync/sync_coordinator.dart';
import 'package:bitacora_web/models/cell_meta.dart';
import 'package:bitacora_web/models/cell_ref.dart';
import 'package:bitacora_web/services/attachment_store.dart';
import 'package:bitacora_web/services/audio_service.dart';
import 'package:bitacora_web/services/audio_storage_service.dart';
import 'package:bitacora_web/services/attachment_pipeline.dart';
import 'package:bitacora_web/services/app_error_reporter.dart';
import 'package:bitacora_web/services/build_info.dart';
import 'package:bitacora_web/services/diagnostics_log.dart';
import 'package:bitacora_web/services/demo_templates.dart';
import 'package:bitacora_web/services/engine_api.dart';
import 'package:bitacora_web/services/engine_config.dart';
import 'package:bitacora_web/services/editor_quick_automation.dart';
import 'package:bitacora_web/services/expression_eval.dart';
import 'package:bitacora_web/services/formula_engine.dart';
import 'package:bitacora_web/services/bitflow_product_service.dart';
import 'package:bitacora_web/services/export_filename.dart';
import 'package:bitacora_web/services/export_flow_outcome.dart';
import 'package:bitacora_web/services/export_share_helper.dart';
import 'package:bitacora_web/services/flowbot.dart';
import 'package:bitacora_web/services/flowbot_macro_store.dart';
import 'package:bitacora_web/services/flowbot_local_model_manager.dart';
import 'package:bitacora_web/services/runtime_flags.dart';
import 'package:bitacora_web/services/keyboard_insets_controller.dart';
import 'package:bitacora_web/services/location_service.dart';
import 'package:bitacora_web/services/location_web_service.dart';
import 'package:bitacora_web/services/network_status.dart';
import 'package:bitacora_web/services/offline_queue_store.dart';
import 'package:bitacora_web/services/package_archive_builder.dart';
import 'package:bitacora_web/services/perf_optimizer.dart';
import 'package:bitacora_web/services/photo_acquire_service.dart';
import 'package:bitacora_web/services/photo_bytes_resolver.dart';
import 'package:bitacora_web/services/photo_json_codec.dart';
import 'package:bitacora_web/services/photo_mime_sniffer.dart';
import 'package:bitacora_web/services/sheet_store.dart';
import 'package:bitacora_web/services/smart_table_paste.dart';
import 'package:bitacora_web/services/speech_service.dart';
import 'package:bitacora_web/services/storage_diagnostics.dart';
import 'package:bitacora_web/services/thumb_decode_lru_cache.dart';
import 'package:bitacora_web/services/web_blob_store.dart';
import 'package:bitacora_web/services/web_attachment_capabilities.dart';
import 'package:bitacora_web/services/web_audio_recorder.dart';
import 'package:bitacora_web/services/web_capabilities.dart';
import 'package:bitacora_web/services/web_flush_signal.dart';
import 'package:bitacora_web/services/web_image_normalizer.dart';
import 'package:bitacora_web/services/export_xlsx_with_photos.dart';
import 'package:bitacora_web/state/grid_selection_controller.dart';
import 'package:bitacora_web/theme/app_theme.dart';
import 'package:bitacora_web/ui/ui.dart';
import 'package:bitacora_web/features/editor/validation/validation_rules.dart';
import 'package:bitacora_web/utils/location_format.dart';
import 'package:bitacora_web/widgets/apple_ui.dart';
import 'package:bitacora_web/widgets/command_palette.dart';
import 'package:bitacora_web/widgets/web_blob_image.dart';

part 'editor_state.dart';
part 'editor_controller.dart';
part 'editor_models.dart';
part 'attachments/attachments_types.dart';
part 'attachments/attachments_utils.dart';
part 'attachments/attachments_controller.dart';
part 'attachments/attachments_view.dart';
part 'attachments/attachment_tile.dart';
part 'attachments/attachment_preview_modal.dart';
part 'dialogs/editor_dialogs.dart';
part 'dialogs/export_dialogs.dart';
part 'dialogs/import_dialogs.dart';
part 'dialogs/confirm_dialogs.dart';
part 'actions/editor_actions.dart';
part 'actions/editor_shortcuts.dart';
part 'widgets/editor_app_bar.dart';
part 'widgets/save_status_chip.dart';
part 'widgets/grid_host.dart';
part 'widgets/mobile_editor_widgets.dart';
part 'widgets/editor_backdrop.dart';
part '../../widgets/mobile_notes_grid.dart';
